version: '3.8'

services:
  telegram-bot:
    build: .
    image: telegram-bot-lab3
    container_name: telegram-bot-lab3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      # Optional: mount logs directory if needed
      - ./logs:/app/logs
    # Optional: resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M